app/dashboard/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^favicon\.ico$', views.FaviconView.as_view()),
    url(r'^$', views.IndexView.as_view(), name='index'),
    #url(r'^session/(?P<pk>[0-9]+)/$', views.SessionView.as_view(), name='session'),
    #url(r'^map/$', views.MapView.as_view(), name='map'),
    url(r'^mobile_sessions/$', views.MobileSessionsView.as_view(), name='mobile_sessions'),
    url(r'^data_values/$', views.DataValuesView.as_view(), name='data_values'),
    url(r'^data_averages/$', views.DataAveragesView.as_view(), name='data_averages'),
    url(r'^coverage/$', views.CoverageView.as_view(), name='coverage'),
    url(r'^about/$', views.AboutView.as_view(), name='about'),
    url(r'^advocacy/$', views.AdvocacyView.as_view(), name='advocacy'),
    url(r'^results/$', views.ResultsView.as_view(), name='results'),
    url(r'^locations/$', views.LocationsView.as_view(), name='locations'),
    url(r'^partners/$', views.PartnersView.as_view(), name='partners'),
    url(r'^references/$', views.ReferencesView.as_view(), name='references'),
    url(r'^ajax/last_updated/$', views.last_updated, name='last_updated'),
    url(r'^ajax/get_users/$', views.get_users, name='get_users'),
    url(r'^ajax/get_sessions/$', views.get_sessions, name='get_sessions'),
    url(r'^ajax/get_streams/$', views.get_streams, name='get_streams'),
    url(r'^ajax/get_measurements/$', views.get_measurements, name='get_measurements'),
    url(r'^ajax/get_neighborhoods/$', views.get_neighborhoods, name='get_neighborhoods'),
    url(r'^ajax/get_tracts/$', views.get_tracts, name='get_tracts'),
    url(r'^ajax/get_wards/$', views.get_wards, name='get_wards'),
    url(r'^ajax/get_hexagons/$', views.get_hexagons, name='get_hexagons'),
    url(r'^ajax/get_zipcodes/$', views.get_zipcodes, name='get_zipcodes'),
    url(r'^ajax/get_averages/$', views.get_averages, name='get_averages'),
    url(r'^ajax/get_counts/$', views.get_counts, name='get_counts')
]

app/elpc_air_quality/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth.views import login, logout

from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'', include('dashboard.urls')),
    url(r'^dashboard/', include('dashboard.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/$', login, {'template_name': 'dashboard/login.html'}, name='login'),
    url(r'^accounts/logout/$', logout, {'next_page': '/'}, name='logout'),
    url(r'^accounts/profile/$', RedirectView.as_view(url='/')),
    url(r'^accounts/$', RedirectView.as_view(url='/')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/dashboard/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import forms

from datetimewidget.widgets import DateTimeWidget, DateWidget, TimeWidget

#from .models import Sessions, Users

#dateTimeOptions = {
#    'format': 'dd/mm/yyyy HH:ii P',
#    'autoclose': True,
#    'showMeridian' : True
#}

weekDays = (
    (2, "Monday"),
    (3, "Tuesday"),
    (4, "Wednesday"),
    (5, "Thursday"),
    (6, "Friday"),
    (7, "Saturday"),
    (1, "Sunday"),
)

class MobileSessionsForm(forms.Form):
    users = forms.MultipleChoiceField(choices=[], required=True)
    all_users = forms.BooleanField(required=False)
    keywords = forms.CharField(required=False)
    sessions = forms.MultipleChoiceField(choices=[], required=True)
    #all_sessions = forms.BooleanField(required=False)
    
class DataValuesForm(forms.Form):
    users = forms.MultipleChoiceField(choices=[], required=True)
    all_users = forms.BooleanField(required=False)
    week_day = forms.MultipleChoiceField(choices=weekDays, required=False)
    start_date = forms.DateField(widget=DateWidget(usel10n=True, bootstrap_version=3))
    end_date = forms.DateField(widget=DateWidget(usel10n=True, bootstrap_version=3))
    start_time = forms.TimeField(widget=TimeWidget(usel10n=True, bootstrap_version=3))
    end_time = forms.TimeField(widget=TimeWidget(usel10n=True, bootstrap_version=3))
    pm_level = forms.ChoiceField(choices=[], required=False)
    geo_type = forms.ChoiceField(required=False)
    geo_boundaries = forms.MultipleChoiceField(choices=[], required=False)
    
class DataAveragesForm(forms.Form):
    week_day = forms.MultipleChoiceField(choices=weekDays, required=False)  
    start_date = forms.DateField(widget=DateWidget(usel10n=True, bootstrap_version=3))
    end_date = forms.DateField(widget=DateWidget(usel10n=True, bootstrap_version=3))
    start_time = forms.TimeField(widget=TimeWidget(usel10n=True, bootstrap_version=3))
    end_time = forms.TimeField(widget=TimeWidget(usel10n=True, bootstrap_version=3))
    geo_type = forms.ChoiceField(required=True)

class CoverageForm(forms.Form):
    users = forms.MultipleChoiceField(choices=[], required=True)
    all_users = forms.BooleanField(required=False)
    geo_type = forms.ChoiceField(required=True)
    
'''
class MapForm(forms.Form):
    users = forms.MultipleChoiceField(choices=[], required=True)
    all_users = forms.BooleanField(required=False)
    keywords = forms.CharField(required=False)
    sessions = forms.MultipleChoiceField(choices=[], required=True)
    all_sessions = forms.BooleanField(required=False)
    #start_time = forms.DateTimeField(required=False)
    #end_time = forms.DateTimeField(required=False)
    
    
    def __init__(self, *args, **kwargs):
        super(MapForm, self).__init__(*args, **kwargs)
        
        # update fields
        self.fields['username'].choices = [(x.pk, x.username) for x in Users.objects.all()]
        self.fields['session'].choices = [(x.pk, x.title) for x in Sessions.objects.all()]
'''
    

        

app/dashboard/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse, JsonResponse
from django.template import loader
from django.shortcuts import get_object_or_404, render
from django.views import generic
from django.core import serializers
from django.db.models import Q, Avg, Count

from django.views.decorators.csrf import csrf_exempt

from .models import Users, Sessions, Streams, Measurements, Neighborhoods, Tracts, Wards, Hexagons, Zipcodes

from .forms import MobileSessionsForm, DataValuesForm, DataAveragesForm, CoverageForm

from functools import reduce
from operator import or_

import json
import datetime
import random

from timeit import default_timer as timer

class FaviconView(generic.RedirectView):
    url='/static/dashboard/favicon.ico'
    permanent=True

class IndexView(generic.TemplateView):
	template_name = 'dashboard/index.html'

#class SessionView(generic.DetailView):
#	template_name = 'dashboard/session.html'
#	model = Sessions

#class MapView(generic.FormView):
#	template_name = 'dashboard/map.html'
#	form_class = MapForm
#	success_url = '/dashboard/'

class AboutView(generic.TemplateView):
	template_name = 'dashboard/about.html'

class AdvocacyView(generic.TemplateView):
	template_name = 'dashboard/advocacy.html'

class LocationsView(generic.TemplateView):
	template_name = 'dashboard/locations.html'

class ResultsView(generic.TemplateView):
	template_name = 'dashboard/results.html'

class PartnersView(generic.TemplateView):
	template_name = 'dashboard/partners.html'

class ReferencesView(generic.TemplateView):
	template_name = 'dashboard/references.html'

class MobileSessionsView(generic.FormView):
	template_name = 'dashboard/mobile_sessions.html'
	form_class = MobileSessionsForm
	success_url = '/dashboard/'

class DataValuesView(generic.FormView):
	template_name = 'dashboard/data_values.html'
	form_class = DataValuesForm
	success_url = '/dashboard/'

class DataAveragesView(generic.FormView):
	template_name = 'dashboard/data_averages.html'
	form_class = DataAveragesForm
	success_url = '/dashboard/'

class CoverageView(generic.FormView):
	template_name = 'dashboard/coverage.html'
	form_class = CoverageForm
	success_url = '/dashboard/'

@csrf_exempt
def last_updated(request):
    measurements = Measurements.objects

    measurement = measurements.latest('time')

    #print measurement.time

    data = {
        'last_updated': measurement.time
    }
    return JsonResponse(data)

def get_users(request):
    user_ids = json.loads(request.POST.get('user_ids', '[]'))

    users = Users.objects

    if user_ids:
        users = users.filter(id__in=user_ids)

    data = {
        'users': json.dumps(list(users.values('id', 'username', 'display')), cls=serializers.json.DjangoJSONEncoder)
    }
    return JsonResponse(data)

def get_sessions(request):
    user_ids = json.loads(request.POST.get('user_ids', '[]'))
    keywords = json.loads(request.POST.get('keywords', '[]'))

    #print user_ids
    #print keywords

    sessions = Sessions.objects

    if user_ids:
        sessions = sessions.filter(user_id__in=user_ids)

    if keywords:
        keywords_query = [Q(title__icontains=keyword) for keyword in keywords]
        sessions = sessions.filter(reduce(or_, keywords_query))

    data = {
        'sessions': json.dumps(list(sessions.values('id', 'title')), cls=serializers.json.DjangoJSONEncoder)
    }
    return JsonResponse(data)

def get_streams(request):
    session_ids = json.loads(request.POST.get('session_ids', '[]'))
    sensor_names = json.loads(request.POST.get('sensor_names', '[]'))
    sample_size = json.loads(request.POST.get('sample_size', '[]'))

    streams = Streams.objects

    if session_ids:
        streams = streams.filter(session__in=session_ids)

    if sensor_names:
        streams = streams.filter(sensor_name__in=sensor_names)

    if sample_size:
        streams = streams.order_by('?')[:sample_size]

    #print "len(streams) = " + str(len(streams))

    data = {
        'streams': json.dumps(list(streams.values('id')), cls=serializers.json.DjangoJSONEncoder)
    }
    return JsonResponse(data)

def get_measurements(request):
    start = timer()
    stream_ids = json.loads(request.POST.get('stream_ids', '[]'))
    geo_type = json.loads(request.POST.get('geo_type', '[]'))
    geo_boundaries = json.loads(request.POST.get('geo_boundaries', '[]'))
    sample_size = json.loads(request.POST.get('sample_size', '[]'))
    min_value = json.loads(request.POST.get('min_value', '[]'))
    max_value = json.loads(request.POST.get('max_value', '[]'))
    week_day = json.loads(request.POST.get('week_day', '[]'))
    start_date = json.loads(request.POST.get('start_date', '[]'))
    end_date = json.loads(request.POST.get('end_date', '[]'))
    start_time = json.loads(request.POST.get('start_time', '[]'))
    end_time = json.loads(request.POST.get('end_time', '[]'))

    '''
    if sample_size:
        measurements = Measurements.objects.raw('SELECT * FROM measurements where RAND() <= %f' % (float(sample_size)/float(Measurements.objects.count())))
    else:
        measurements = Measurements.objects
    '''
    measurements = Measurements.objects

    if sample_size:
        measurements = measurements.order_by('?')[:sample_size]

    if stream_ids:
        measurements = measurements.filter(stream__in=stream_ids)

    if geo_type == 'tract':
        measurements = measurements.filter(tract__in=geo_boundaries)
    elif geo_type == 'neighborhood':
        measurements = measurements.filter(neighborhood__in=geo_boundaries)
    elif geo_type == 'ward':
        measurements = measurements.filter(ward__in=geo_boundaries)
    elif geo_type == 'hexagon':
        measurements = measurements.filter(hexagon__in=geo_boundaries)
    elif geo_type == 'zipcode':
        measurements = measurements.filter(zipcode__in=geo_boundaries)

    if min_value:
        measurements = measurements.filter(value__gte=min_value)

    if max_value:
        measurements = measurements.filter(value__lt=max_value)

    if week_day:
        measurements = measurements.filter(time__week_day__in=week_day)

    if start_date:
        measurements = measurements.filter(time__date__gte=datetime.datetime.strptime(start_date, "%Y-%m-%d").date())

    if end_date:
        measurements = measurements.filter(time__date__lte=datetime.datetime.strptime(end_date, "%Y-%m-%d").date())

    if start_time:
        measurements = measurements.filter(time__time__gte=datetime.datetime.strptime(start_time, "%H:%M:%S").time())

    if end_time:
        measurements = measurements.filter(time__time__lte=datetime.datetime.strptime(end_time, "%H:%M:%S").time())

    #print "len(measurements) = " + str(measurements.count())
    #print "filters = " + str(timer() - start)

    data = {
        'measurements': json.dumps(list(measurements.values('id', 'stream_id', 'value', 'latitude', 'longitude', 'time')), cls=serializers.json.DjangoJSONEncoder)
    }
    #print "json = " + str(timer() - start)
    return JsonResponse(data)

def get_neighborhoods(request):
    neighborhood_ids = json.loads(request.POST.get('neighborhood_ids', '[]'))

    neighborhoods = Neighborhoods.objects

    if neighborhood_ids:
        neighborhoods = neighborhoods.filter(id__in=neighborhood_ids)


    data = {
        'neighborhoods': json.dumps(list(neighborhoods.order_by('display').values('id', 'display', 'geo')), cls=serializers.json.DjangoJSONEncoder)
    }
    return JsonResponse(data)

def get_tracts(request):
    tract_ids = json.loads(request.POST.get('tract_ids', '[]'))

    tracts = Tracts.objects

    if tract_ids:
        tracts = tracts.filter(id__in=tract_ids)

    data = {
        'tracts': json.dumps(list(tracts.values('id', 'display', 'geo')), cls=serializers.json.DjangoJSONEncoder)
    }
    return JsonResponse(data)

def get_wards(request):
    ward_ids = json.loads(request.POST.get('ward_ids', '[]'))

    wards = Wards.objects

    if ward_ids:
        wards = wards.filter(id__in=ward_ids)

    data = {
        'wards': json.dumps(list(wards.values('id', 'display', 'geo')), cls=serializers.json.DjangoJSONEncoder)
    }
    return JsonResponse(data)

@csrf_exempt
def get_hexagons(request):
    hexagon_ids = json.loads(request.POST.get('hexagon_ids', '[]'))
    min_counts = json.loads(request.POST.get('min_counts', '[]'))

    hexagons = Hexagons.objects

    if hexagon_ids:
        hexagons = hexagons.filter(id__in=hexagon_ids)

    if min_counts:
        hexagons = hexagons.filter(counts__gte=min_counts)

    data = {
        'hexagons': json.dumps(list(hexagons.values('id', 'display', 'geo', 'counts', 'harmful', 'good', 'average', 'health_score')), cls=serializers.json.DjangoJSONEncoder)
    }
    return JsonResponse(data)

def get_zipcodes(request):
    zipcode_ids = json.loads(request.POST.get('zipcode_ids', '[]'))

    zipcodes = Zipcodes.objects

    if zipcode_ids:
        zipcodes = zipcodes.filter(id__in=zipcode_ids)

    data = {
        'zipcodes': json.dumps(list(zipcodes.values('id', 'display', 'geo')), cls=serializers.json.DjangoJSONEncoder)
    }
    return JsonResponse(data)

def get_averages(request):
    start = timer()
    stream_ids = json.loads(request.POST.get('stream_ids', '[]'))
    geo_type = json.loads(request.POST.get('geo_type', '[]'))
    week_day = json.loads(request.POST.get('week_day', '[]'))
    start_date = json.loads(request.POST.get('start_date', '[]'))
    end_date = json.loads(request.POST.get('end_date', '[]'))
    start_time = json.loads(request.POST.get('start_time', '[]'))
    end_time = json.loads(request.POST.get('end_time', '[]'))
    sample_size = json.loads(request.POST.get('sample_size', '[]'))

    measurements = Measurements.objects

    if sample_size:
        pass
    #    print "sample_size = " + str(sample_size)
    #    #measurements = measurements.order_by('?')[:sample_size]

    if stream_ids:

app/dashboard/templates/dashboard/data_averages.html
{% extends 'dashboard/base.html' %}

{% load bootstrap3 %}

{% load static %}

{% block bootstrap3_extra_head %}
    <!-- leaflet css -->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css"
        integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ=="
        crossorigin=""/>

    <!-- dashboard css -->
    <link rel="stylesheet" href="{% static 'dashboard/dashboard.css' %}"/>
{% endblock %}

{% block title %}Data Averages -{% endblock %}

{% block content %}
    <div class="alert text-white bg-teal" role="alert">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <p>Select a geographic boundary to view averages of PM2.5 data by location.</p>
 
        <p>Once boundary type is selected, press “Map” and wait for the data to appear. Map data can be downloaded using the “Download” button. Map views can also be saved using the arrow key on the map.</p>
    </div>
    
    <form role="form" id="id_request" class="form-horizontal p-3"> <!!! method="post" !!!>
        {% csrf_token %}
        {% bootstrap_form form layout="horizontal" %}
        {% buttons %}
			<div style="padding-left:15px;">
				<button type="submit" id="id_submit" class="btn btn-primary">Map</button>
				<button type="reset" id="id_reset" class="btn btn-primary">Clear</button>
				<button type="button" id="id_download" class="btn btn-primary">Download</button>
			</div>
        {% endbuttons %}
    </form>

    <div id="id_map">
    </div>
{% endblock %}


{% block bootstrap3_extra_script %}
    <!-- leaflet js -->
    <script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js"
       integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw=="
       crossorigin="">
    </script>
    
    <!-- leaflet easyPrint -->
    <script src="https://cdn.jsdelivr.net/gh/rowanwins/leaflet-easyPrint@gh-pages/dist/bundle.js">
    </script>
   
    <!-- leaflet omnivore -->
    <script src='//api.tiles.mapbox.com/mapbox.js/plugins/leaflet-omnivore/v0.3.1/leaflet-omnivore.min.js'></script>
    
    <!-- leaflet spin -->
    <script src="https://cdn.jsdelivr.net/gh/makinacorpus/Leaflet.Spin@gh-pages/spin/spin.js" charset="utf-8"></script>
    <script src="https://cdn.jsdelivr.net/gh/makinacorpus/Leaflet.Spin@gh-pages/leaflet.spin.min.js" charset="utf-8"></script>
    
    <!-- json2csv -->
    <script src="https://cdn.jsdelivr.net/gh/justdesigncoop/json2csv@master/json2csv.min.js" charset="utf-8"></script>
    
    <!-- dashboard functions -->
    <script src="{% static 'dashboard/dashboard.js' %}"  type="text/javascript">
    </script> 
    
    <!-- jquery cookie -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>

    <script>
        /*----------------------------------------------------------------------------
          global vars setup
         *----------------------------------------------------------------------------*/         
        var geoType = geoTypes.NONE;
        
        var averages = [];
        
        var csvData = [];
        
        /*----------------------------------------------------------------------------
          map setup
         *----------------------------------------------------------------------------*/
        // tile layers
        var streets = L.tileLayer('https://stamen-tiles-{s}.a.ssl.fastly.net/terrain/{z}/{x}/{y}{r}.{ext}', {
            attribution: 'Map tiles by <a href="http://stamen.com">Stamen Design</a>, <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a> &mdash; Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
            subdomains: 'abcd',
            minZoom: 0,
            maxZoom: 18,
            ext: 'png'
        });

        var light = L.tileLayer('https://stamen-tiles-{s}.a.ssl.fastly.net/toner-lite/{z}/{x}/{y}{r}.{ext}', {
            attribution: 'Map tiles by <a href="http://stamen.com">Stamen Design</a>, <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a> &mdash; Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
            subdomains: 'abcd',
            minZoom: 0,
            maxZoom: 20,
            ext: 'png'
        });
        
        // layer groups
        var geo = L.featureGroup([]);
        
        // map
        var map = L.map('id_map', {
            center: [41.8781, -87.6298],
            zoom: 13,
            preferCanvas: true,
            layers: [streets, geo],
        });
        
        // control layers
        var baseMaps = {
            "Color": streets,
            "Greyscale": light,
        };
        
        var overlayMaps = {
            "Geo": geo,
        };
        
        L.control.layers(baseMaps, overlayMaps).addTo(map);
        
        var printPlugin = L.easyPrint({
      		sizeModes: ['Current', 'A4Landscape', 'A4Portrait'],
      		filename: 'map',
      		exportOnly: true,
      		hideControlContainer: true
		}).addTo(map);
		
		// legend       
	    var legend = L.control({position: 'bottomright'});

	    legend.onAdd = function(map) {
		    var div = L.DomUtil.create('div', 'info legend');
		    
		    div.innerHTML = getLegend("PM2.5 ug/m3", pmLevels, colorMap);
		    
		    return div;
	    };

	    legend.addTo(map);
        
        /*----------------------------------------------------------------------------
          document ready callback
         *----------------------------------------------------------------------------*/   
        $(document).ready(function() {
            // disable download button
            $("#id_download").prop("disabled", true);
            
            // populate geo types select
            for(var key in geoTypes.properties) {
                if((key == geoTypes.NONE) || (key == geoTypes.HEXAGONS)) {
                    continue;
                }
                else {
                    $("#id_geo_type").append($("<option />").val(geoTypes.properties[key].value).text(geoTypes.properties[key].name));
                }
            }
        });  
        
        /*----------------------------------------------------------------------------
          submit callback
         *----------------------------------------------------------------------------*/ 
        $("#id_request").on('submit', function(e) {
            // prevent default form action
            e.preventDefault();
            
            geoType = parseInt($('#id_geo_type').val(), 10);
            //console.log(geoType);
            
            // get all streams     
            getStreams({
                'session_ids': [],
                'sensor_names': sensorNames,
                }, streamsCallback);
            
            // start spin
            map.spin(true);
        });
        
        /*----------------------------------------------------------------------------
          reset callback
         *----------------------------------------------------------------------------*/  
        $("#id_request").on('reset', function(e) {
            // prevent default form action
            e.preventDefault();
            
            geoType = geoTypes.NONE;
            
            geo.clearLayers();
            
            // disable download button
            $("#id_download").prop("disabled", true)
        });
        
        /*----------------------------------------------------------------------------
          download callback
         *----------------------------------------------------------------------------*/  
        $("#id_download").on('click', function(e) {            
            //console.log("download");
            
            // convert to csv and download
            csvConverter.convert(csvData);
        });
        
        /*----------------------------------------------------------------------------
          streams data callback
         *----------------------------------------------------------------------------*/
        function streamsCallback(data) {
            var streams = JSON.parse(data['streams']);
            //console.log(streams);
            
            // iterate through streams, get stream ids
            var stream_ids = [];
            for(i = 0; i < streams.length; ++i) {
                // check for air quality sensor
                //if(streams[i]['sensor_name'] == 'AirBeam-PM') {
				//if(checkSensorName(streams[i]['sensor_name'])) {
                    stream_ids.push(streams[i]['id']);
                //}
            }
			
			// get dates and times
			var week_day = getSelectedOptions("#id_week_day");
			var start_date = $("[name='start_date']").val();
			var end_date = $("[name='end_date']").val();
			var start_time = $("[name='start_time']").val()
			var end_time = $("[name='end_time']").val()
            
            // get averages
            getAverages({
                'stream_ids': stream_ids,
                'geo_type': geoTypes.properties[geoType].column,
                'week_day': week_day,
                'start_date': start_date,
				'end_date': end_date,
				'start_time': start_time,
				'end_time': end_time,
				'sample_size': sampleSize,
                }, averagesCallback);
        }
        
        /*----------------------------------------------------------------------------
          averages data callback
         *----------------------------------------------------------------------------*/
        function averagesCallback(data) {
            averages = JSON.parse(data['averages']);
            //console.log(averages);
            
            // geo type callback
            var cb = geoTypes.properties[geoType].cb;
            if(cb) {
                cb([], geoCallback);
            }
        }
        
        /*----------------------------------------------------------------------------
          geo type select callback
         *----------------------------------------------------------------------------*/
        $("#id_geo_type").change(function() {
        });
        
        /*----------------------------------------------------------------------------
          geo data callback
         *----------------------------------------------------------------------------*/
        function geoCallback(data) {
            // check geo type
            var table = geoTypes.properties[geoType].table;
            var geo_data = JSON.parse(data[table]);
            //console.log(geo_data);
            
            geo.clearLayers();
            
            // reset csv data
            csvData = [];
            
            // add to list, draw neighborhoods
            for (i = 0; i < geo_data.length; ++i) {
                // check averages
                var pk = geo_data[i]['id'];
				var display = geo_data[i]['display'];
                var value = averages[pk];
                
                // fill color
                var color = '#fff';
                var opacity = 0.0;
                if(value != undefined) {
                    color = colorMap(value);
                    opacity = 0.7;
                    
                    // add to csv data
                    csvData.push({'id': pk, 'boundary': display, 'value': value});
                }
                
                // skip default location (empty multipolygon)
                if(pk == defaultLoc) {
                    continue;
                }   
                
                var multi_polygon = omnivore.wkt.parse(geo_data[i]['geo']);
                
                multi_polygon.setStyle({
                    fillColor: color,
                    fillOpacity: opacity,
                    color: '#444',
                    weight: 3,
                    opacity: 1.0,
                });
                
                // popup text
                if(value != undefined) {
                    var popup = "<table class=\"table table-bordered table-striped\"> \
                        <tr><th>Boundary</th><td>" + display + "</td></tr> \
                        <tr><th>PM2.5</th><td>" + value.toFixed(2) + "</td></tr> \
                        </table>"
                    multi_polygon.bindPopup(popup)
                }
                
                geo.addLayer(multi_polygon);
            }
            
            // stop spin
            map.spin(false);
            
            // enable download button
            $("#id_download").prop("disabled", false);
            
            // fit map
            map.fitBounds(geo.getBounds());
        }
    </script>
{% endblock %}

app/dashboard/templates/dashboard/session.html
{% extends 'dashboard/base.html' %}

{% load bootstrap3 %}

{% block title %}session view{% endblock %}

{% block content %}
	{{ object }}
{% endblock %}